# search-cell config
search_space: tss

model:
  super_type: basic
  name: generic
  C: 16
  N: 5
  max_nodes: 4
  track_running_stats: False
  affine:  True
  train_arch_parameters: True

arch_learning_rate: 3.0e-4
arch_weight_decay: 1.0e-3
arch_eps: 1.e-8
drop_path_rate: null


criterion: Softmax
LR: 0.025

# optimizer config.
optim: SGD
momentum: 0.9
nesterov: True
decay: 0.0005

# Scheuler config.
scheduler: cos
gamma: 0.99
gammas: null
milstones: null
eta_min: 0.001

epochs: 50
warmup: 0
batch_size: 2048
test_batch_size: 16384

grouping: alpha  
group_id: 0

metric: val_acc  # or [val_acc, train_loss]
warmup_epochs: 80 # choose from 100, 80, 40, 20
warmup_lr: 0.025
warmup_lr_min: 0.001
warmup_batch_size: 1536
warmup_mode: joint

train_lr: 0.025
train_lr_min: 0.
train_epochs: 200 # the total number opochs to train if with full exploitation.
train_batch_size: 1536
topk: 3 # re-examize the topk subnets to reduce variance.
stabilize_epochs: 0
re_init: False
test_batch_size: 16384

# default cfg
data:
  dataset: cifar10 # choose from cifar10, cifar100, ImageNet16-120
  data_path: ./data
enable_valid: True

rand_seed: -1 # if negative, using a random seed
workers: 6

# api
use_api: True
eval_candidate_num: 100

# log
load_path: null
log_dir: ./output/search/
print_freq: 100

wandb:
  use_wandb: True
  project: CIFAR-10 